//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesDatas.Language_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language_English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MesDatas.Language_Resources.language_English", typeof(language_English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check if the account password is correct.
        /// </summary>
        public static string checkIdorpwd {
            get {
                return ResourceManager.GetString("checkIdorpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string comboBox2_Items {
            get {
                return ResourceManager.GetString("comboBox2.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swipe.
        /// </summary>
        public static string comboBox2_Items1 {
            get {
                return ResourceManager.GetString("comboBox2.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string d1Barcode {
            get {
                return ResourceManager.GetString("d1Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationName.
        /// </summary>
        public static string d1StationName {
            get {
                return ResourceManager.GetString("d1StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Results.
        /// </summary>
        public static string d2CPJG {
            get {
                return ResourceManager.GetString("d2CPJG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product barcode.
        /// </summary>
        public static string d2CPTM {
            get {
                return ResourceManager.GetString("d2CPTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Model.
        /// </summary>
        public static string d2CPXH {
            get {
                return ResourceManager.GetString("d2CPXH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test time.
        /// </summary>
        public static string d2CSSJ {
            get {
                return ResourceManager.GetString("d2CSSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operator.
        /// </summary>
        public static string d2CZY {
            get {
                return ResourceManager.GetString("d2CZY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string d2NO {
            get {
                return ResourceManager.GetString("d2NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload status.
        /// </summary>
        public static string d2SCZT {
            get {
                return ResourceManager.GetString("d2SCZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string d3Name {
            get {
                return ResourceManager.GetString("d3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        public static string d3Value {
            get {
                return ResourceManager.GetString("d3Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Value.
        /// </summary>
        public static string d4BZZ {
            get {
                return ResourceManager.GetString("d4BZZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result.
        /// </summary>
        public static string d4CSJG {
            get {
                return ResourceManager.GetString("d4CSJG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test item.
        /// </summary>
        public static string d4CSXM {
            get {
                return ResourceManager.GetString("d4CSXM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO..
        /// </summary>
        public static string d4NO {
            get {
                return ResourceManager.GetString("d4NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Value.
        /// </summary>
        public static string d4SJZ {
            get {
                return ResourceManager.GetString("d4SJZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Value.
        /// </summary>
        public static string d4SXZ {
            get {
                return ResourceManager.GetString("d4SXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Value.
        /// </summary>
        public static string d4XXZ {
            get {
                return ResourceManager.GetString("d4XXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Rules.
        /// </summary>
        public static string d5BarcodeRule {
            get {
                return ResourceManager.GetString("d5BarcodeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixture Number.
        /// </summary>
        public static string d5FixtureID {
            get {
                return ResourceManager.GetString("d5FixtureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Number.
        /// </summary>
        public static string d5ID {
            get {
                return ResourceManager.GetString("d5ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string d5PCode {
            get {
                return ResourceManager.GetString("d5PCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string d5PName {
            get {
                return ResourceManager.GetString("d5PName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code Verification.
        /// </summary>
        public static string d5QRCode {
            get {
                return ResourceManager.GetString("d5QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加失败/Add Failed/เพิ่มไม่สำเร็จ.
        /// </summary>
        public static string ErrorBtnAdd {
            get {
                return ResourceManager.GetString("ErrorBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败/Delete Failed/ลบไม่สำเร็จ.
        /// </summary>
        public static string ErrorBtnDelete {
            get {
                return ResourceManager.GetString("ErrorBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失败/Save Failed/บันทึกไม่สำเร็จ.
        /// </summary>
        public static string ErrorBtnSave {
            get {
                return ResourceManager.GetString("ErrorBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新失败/Update Failed/อัปเดตไม่สำเร็จ.
        /// </summary>
        public static string ErrorBtnUpdate {
            get {
                return ResourceManager.GetString("ErrorBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the production work order number:.
        /// </summary>
        public static string InputBox {
            get {
                return ResourceManager.GetString("InputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time Not inputted (Reminder: Exit the system without entering 3 times).
        /// </summary>
        public static string InputBox1 {
            get {
                return ResourceManager.GetString("InputBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production work order.
        /// </summary>
        public static string InputBoxName {
            get {
                return ResourceManager.GetString("InputBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your account and password.
        /// </summary>
        public static string inputTip {
            get {
                return ResourceManager.GetString("inputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on line.
        /// </summary>
        public static string loginMode {
            get {
                return ResourceManager.GetString("loginMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off line.
        /// </summary>
        public static string loginMode1 {
            get {
                return ResourceManager.GetString("loginMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status display: The current employee card does not have swipe login permission!.
        /// </summary>
        public static string loginType {
            get {
                return ResourceManager.GetString("loginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Logintype1 {
            get {
                return ResourceManager.GetString("Logintype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe card.
        /// </summary>
        public static string Logintype2 {
            get {
                return ResourceManager.GetString("Logintype2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowerLimit.
        /// </summary>
        public static string LowerLimit {
            get {
                return ResourceManager.GetString("LowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select login mode.
        /// </summary>
        public static string ModeTip {
            get {
                return ResourceManager.GetString("ModeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have offline login permission, please select again!.
        /// </summary>
        public static string offlineTip {
            get {
                return ResourceManager.GetString("offlineTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation.
        /// </summary>
        public static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check Online Parameters.
        /// </summary>
        public static string OT_CheckParam {
            get {
                return ResourceManager.GetString("OT_CheckParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Remove Product to Continue.
        /// </summary>
        public static string OT_Continue {
            get {
                return ResourceManager.GetString("OT_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload Again.
        /// </summary>
        public static string OT_Reupload {
            get {
                return ResourceManager.GetString("OT_Reupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Complete.
        /// </summary>
        public static string OT_Scaned {
            get {
                return ResourceManager.GetString("OT_Scaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Fixture Scan.
        /// </summary>
        public static string OT_ScanFixture {
            get {
                return ResourceManager.GetString("OT_ScanFixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please continue to scan the Fixture QR Code..
        /// </summary>
        public static string OT_ScanFixtureContinue {
            get {
                return ResourceManager.GetString("OT_ScanFixtureContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Start Production.
        /// </summary>
        public static string OT_StartProduce {
            get {
                return ResourceManager.GetString("OT_StartProduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station 1 Test NG: Unable to enter Station 2.
        /// </summary>
        public static string OT_Station1NG {
            get {
                return ResourceManager.GetString("OT_Station1NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait….
        /// </summary>
        public static string OT_Wait {
            get {
                return ResourceManager.GetString("OT_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Barcode Scan.
        /// </summary>
        public static string OT_WaitingScan {
            get {
                return ResourceManager.GetString("OT_WaitingScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加成功/Add Successful/เพิ่มสำเร็จ.
        /// </summary>
        public static string PassBtnAdd {
            get {
                return ResourceManager.GetString("PassBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除成功/Delete Successful/ลบสำเร็จ.
        /// </summary>
        public static string PassBtnDelete {
            get {
                return ResourceManager.GetString("PassBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功/Save Successful/บันทึกสำเร็จ.
        /// </summary>
        public static string PassBtnSave {
            get {
                return ResourceManager.GetString("PassBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新成功/Update Successful/อัปเดตสำเร็จ.
        /// </summary>
        public static string PassBtnUpdate {
            get {
                return ResourceManager.GetString("PassBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device connection failed, please restart the software or restart the machine!.
        /// </summary>
        public static string plcConn {
            get {
                return ResourceManager.GetString("plcConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status display: Port opening failed!.
        /// </summary>
        public static string portNG {
            get {
                return ResourceManager.GetString("portNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status display: Port opened successfully!.
        /// </summary>
        public static string portOK {
            get {
                return ResourceManager.GetString("portOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status display: Port occupied!.
        /// </summary>
        public static string portType {
            get {
                return ResourceManager.GetString("portType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card reader port and device number acquisition failed, please maintain first!.
        /// </summary>
        public static string posType {
            get {
                return ResourceManager.GetString("posType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the card reader.
        /// </summary>
        public static string readCard_Close {
            get {
                return ResourceManager.GetString("readCard_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the card reader.
        /// </summary>
        public static string readCard_Open {
            get {
                return ResourceManager.GetString("readCard_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status display: Card reading successful!.
        /// </summary>
        public static string readCardOK {
            get {
                return ResourceManager.GetString("readCardOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Mismatch.
        /// </summary>
        public static string RSBarcode_Dismach {
            get {
                return ResourceManager.GetString("RSBarcode_Dismach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Barcode Format.
        /// </summary>
        public static string RSBarcode_Fault {
            get {
                return ResourceManager.GetString("RSBarcode_Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MES Validation Failed.
        /// </summary>
        public static string RSBarcode_NG {
            get {
                return ResourceManager.GetString("RSBarcode_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Validation Rule.
        /// </summary>
        public static string RSBarcode_NoRule {
            get {
                return ResourceManager.GetString("RSBarcode_NoRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Not Found.
        /// </summary>
        public static string RSBarcode_Null {
            get {
                return ResourceManager.GetString("RSBarcode_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Validated.
        /// </summary>
        public static string RSBarcode_OK {
            get {
                return ResourceManager.GetString("RSBarcode_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Barcode.
        /// </summary>
        public static string RSBarcode_Repeat {
            get {
                return ResourceManager.GetString("RSBarcode_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved.
        /// </summary>
        public static string RSData_Saved {
            get {
                return ResourceManager.GetString("RSData_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Data….
        /// </summary>
        public static string RSData_Saving {
            get {
                return ResourceManager.GetString("RSData_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Data….
        /// </summary>
        public static string RSData_StartReading {
            get {
                return ResourceManager.GetString("RSData_StartReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Data….
        /// </summary>
        public static string RSData_Uploading {
            get {
                return ResourceManager.GetString("RSData_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Failed.
        /// </summary>
        public static string RSData_UploadNG {
            get {
                return ResourceManager.GetString("RSData_UploadNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Successful.
        /// </summary>
        public static string RSData_UploadOK {
            get {
                return ResourceManager.GetString("RSData_UploadOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixture ID Verification Failed .
        /// </summary>
        public static string RSFixture_NG {
            get {
                return ResourceManager.GetString("RSFixture_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fixture Validation Required.
        /// </summary>
        public static string RSFixture_NotRequire {
            get {
                return ResourceManager.GetString("RSFixture_NotRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixture ID Verified.
        /// </summary>
        public static string RSFixture_OK {
            get {
                return ResourceManager.GetString("RSFixture_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixture Validation Required.
        /// </summary>
        public static string RSFixture_RequireValidate {
            get {
                return ResourceManager.GetString("RSFixture_RequireValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Fixture....
        /// </summary>
        public static string RSFixture_Validating {
            get {
                return ResourceManager.GetString("RSFixture_Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Verification Failed.
        /// </summary>
        public static string RSMaterial_NG {
            get {
                return ResourceManager.GetString("RSMaterial_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Verified.
        /// </summary>
        public static string RSMaterial_OK {
            get {
                return ResourceManager.GetString("RSMaterial_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode not found at Station 1..
        /// </summary>
        public static string RSStation_NoData {
            get {
                return ResourceManager.GetString("RSStation_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result for Station 1 is NG.
        /// </summary>
        public static string RSStation_Station1NG {
            get {
                return ResourceManager.GetString("RSStation_Station1NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the test at Station 1 first.
        /// </summary>
        public static string RSStation_TobeCompleted {
            get {
                return ResourceManager.GetString("RSStation_TobeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local User Verified.
        /// </summary>
        public static string RSUser_OfflineOK {
            get {
                return ResourceManager.GetString("RSUser_OfflineOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online User Verified.
        /// </summary>
        public static string RSUser_OnlineNG {
            get {
                return ResourceManager.GetString("RSUser_OnlineNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User verification successful.
        /// </summary>
        public static string RSUser_OnlineOK {
            get {
                return ResourceManager.GetString("RSUser_OnlineOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying User….
        /// </summary>
        public static string RSUser_Verifing {
            get {
                return ResourceManager.GetString("RSUser_Verifing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current card number has multiple accounts and cannot be swiped to log in!.
        /// </summary>
        public static string serchType {
            get {
                return ResourceManager.GetString("serchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standby.
        /// </summary>
        public static string Standby {
            get {
                return ResourceManager.GetString("Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System default data cannot be deleted.
        /// </summary>
        public static string SystemDefaultDataNotDel {
            get {
                return ResourceManager.GetString("SystemDefaultDataNotDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string UploadState_Failed {
            get {
                return ResourceManager.GetString("UploadState_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string UploadState_Local {
            get {
                return ResourceManager.GetString("UploadState_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string UploadState_Success {
            get {
                return ResourceManager.GetString("UploadState_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpperLimit.
        /// </summary>
        public static string UpperLimit {
            get {
                return ResourceManager.GetString("UpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan the fixture.
        /// </summary>
        public static string Wait_scan_Jig {
            get {
                return ResourceManager.GetString("Wait_scan_Jig", resourceCulture);
            }
        }
    }
}
