//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesDatas.Language_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language_Chinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_Chinese() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MesDatas.Language_Resources.language_Chinese", typeof(language_Chinese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码校验失败.
        /// </summary>
        public static string barCode_NG {
            get {
                return ResourceManager.GetString("barCode_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码校验通过.
        /// </summary>
        public static string barCode_OK {
            get {
                return ResourceManager.GetString("barCode_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码重复扫描.
        /// </summary>
        public static string barCode_repeat {
            get {
                return ResourceManager.GetString("barCode_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未获取到条码，请重新扫描！.
        /// </summary>
        public static string barCode_State {
            get {
                return ResourceManager.GetString("barCode_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始读取数据.
        /// </summary>
        public static string begin_read_data {
            get {
                return ResourceManager.GetString("begin_read_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.btw)|*.btw.
        /// </summary>
        public static string cboFileFormat_TCP_Items {
            get {
                return ResourceManager.GetString("cboFileFormat_TCP.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.prn)|*.prn.
        /// </summary>
        public static string cboFileFormat_TCP_Items1 {
            get {
                return ResourceManager.GetString("cboFileFormat_TCP.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查联机参数.
        /// </summary>
        public static string Check_param {
            get {
                return ResourceManager.GetString("Check_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查账号密码是否正确.
        /// </summary>
        public static string checkIdorpwd {
            get {
                return ResourceManager.GetString("checkIdorpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品名称.
        /// </summary>
        public static string CName {
            get {
                return ResourceManager.GetString("CName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码登录.
        /// </summary>
        public static string comboBox2_Items {
            get {
                return ResourceManager.GetString("comboBox2.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷卡登录.
        /// </summary>
        public static string comboBox2_Items1 {
            get {
                return ResourceManager.GetString("comboBox2.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请取下产品继续生产.
        /// </summary>
        public static string Continue_production {
            get {
                return ResourceManager.GetString("Continue_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品编号.
        /// </summary>
        public static string d2CPBH {
            get {
                return ResourceManager.GetString("d2CPBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品结果.
        /// </summary>
        public static string d2CPJG {
            get {
                return ResourceManager.GetString("d2CPJG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品条码.
        /// </summary>
        public static string d2CPTM {
            get {
                return ResourceManager.GetString("d2CPTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试时间.
        /// </summary>
        public static string d2CSSJ {
            get {
                return ResourceManager.GetString("d2CSSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作员.
        /// </summary>
        public static string d2CZY {
            get {
                return ResourceManager.GetString("d2CZY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string d2No {
            get {
                return ResourceManager.GetString("d2No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传状态.
        /// </summary>
        public static string d2SCZT {
            get {
                return ResourceManager.GetString("d2SCZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加失败.
        /// </summary>
        public static string ErrorBtnAdd {
            get {
                return ResourceManager.GetString("ErrorBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败.
        /// </summary>
        public static string ErrorBtnDelete {
            get {
                return ResourceManager.GetString("ErrorBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失败.
        /// </summary>
        public static string ErrorBtnSave {
            get {
                return ResourceManager.GetString("ErrorBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新失败.
        /// </summary>
        public static string ErrorBtnUpdate {
            get {
                return ResourceManager.GetString("ErrorBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工装编号验证失败.
        /// </summary>
        public static string Fixture_NG {
            get {
                return ResourceManager.GetString("Fixture_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工装编号验证通过.
        /// </summary>
        public static string Fixture_OK {
            get {
                return ResourceManager.GetString("Fixture_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配方编号.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入生产工单号:.
        /// </summary>
        public static string InputBox {
            get {
                return ResourceManager.GetString("InputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次未输入(提示：3次未输入退出系统).
        /// </summary>
        public static string InputBox1 {
            get {
                return ResourceManager.GetString("InputBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产工单号.
        /// </summary>
        public static string InputBoxName {
            get {
                return ResourceManager.GetString("InputBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入账号和密码.
        /// </summary>
        public static string inputTip {
            get {
                return ResourceManager.GetString("inputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线.
        /// </summary>
        public static string loginMode {
            get {
                return ResourceManager.GetString("loginMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 离线.
        /// </summary>
        public static string loginMode1 {
            get {
                return ResourceManager.GetString("loginMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态显示：当前员工卡无刷卡登录权限！.
        /// </summary>
        public static string loginType {
            get {
                return ResourceManager.GetString("loginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string Logintype1 {
            get {
                return ResourceManager.GetString("Logintype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷卡.
        /// </summary>
        public static string Logintype2 {
            get {
                return ResourceManager.GetString("Logintype2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品编码.
        /// </summary>
        public static string MateName {
            get {
                return ResourceManager.GetString("MateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物料验证失败，请重新扫描！.
        /// </summary>
        public static string material_NG {
            get {
                return ResourceManager.GetString("material_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物料验证通过.
        /// </summary>
        public static string material_OK {
            get {
                return ResourceManager.GetString("material_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联机数据上传中.
        /// </summary>
        public static string Mes_upload {
            get {
                return ResourceManager.GetString("Mes_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联机数据上传失败.
        /// </summary>
        public static string Mes_upload_NG {
            get {
                return ResourceManager.GetString("Mes_upload_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联机数据上传成功.
        /// </summary>
        public static string Mes_upload_OK {
            get {
                return ResourceManager.GetString("Mes_upload_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择登录模式.
        /// </summary>
        public static string ModeTip {
            get {
                return ResourceManager.GetString("ModeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您没有离线登录权限、请重新选择！.
        /// </summary>
        public static string offlineTip {
            get {
                return ResourceManager.GetString("offlineTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单机用户验证成功.
        /// </summary>
        public static string OfflineUser_OK {
            get {
                return ResourceManager.GetString("OfflineUser_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联机用户验证失败.
        /// </summary>
        public static string onlineUser_NG {
            get {
                return ResourceManager.GetString("onlineUser_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联机用户验证成功.
        /// </summary>
        public static string onlineUser_OK {
            get {
                return ResourceManager.GetString("onlineUser_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加成功.
        /// </summary>
        public static string PassBtnAdd {
            get {
                return ResourceManager.GetString("PassBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除成功.
        /// </summary>
        public static string PassBtnDelete {
            get {
                return ResourceManager.GetString("PassBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功.
        /// </summary>
        public static string PassBtnSave {
            get {
                return ResourceManager.GetString("PassBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新成功.
        /// </summary>
        public static string PassBtnUpdate {
            get {
                return ResourceManager.GetString("PassBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC连接失败，请重启软件或重启机台！.
        /// </summary>
        public static string plcConn {
            get {
                return ResourceManager.GetString("plcConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态显示：端口打开失败！.
        /// </summary>
        public static string portNG {
            get {
                return ResourceManager.GetString("portNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态显示：端口打开成功！.
        /// </summary>
        public static string portOK {
            get {
                return ResourceManager.GetString("portOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态显示：端口被占用！.
        /// </summary>
        public static string portType {
            get {
                return ResourceManager.GetString("portType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读卡器端口、设备号获取失败、请先维护！.
        /// </summary>
        public static string posType {
            get {
                return ResourceManager.GetString("posType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请重新上传.
        /// </summary>
        public static string Re_upload {
            get {
                return ResourceManager.GetString("Re_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地数据保存中.
        /// </summary>
        public static string Read_data {
            get {
                return ResourceManager.GetString("Read_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地数据保存完成.
        /// </summary>
        public static string Read_data_OK {
            get {
                return ResourceManager.GetString("Read_data_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭读卡器.
        /// </summary>
        public static string readCard_Close {
            get {
                return ResourceManager.GetString("readCard_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开读卡器.
        /// </summary>
        public static string readCard_Open {
            get {
                return ResourceManager.GetString("readCard_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态显示：读卡成功！.
        /// </summary>
        public static string readCardOK {
            get {
                return ResourceManager.GetString("readCardOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫码完成.
        /// </summary>
        public static string ScanBarCode_OK {
            get {
                return ResourceManager.GetString("ScanBarCode_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前卡号存在多个账户、不能刷卡登录！.
        /// </summary>
        public static string serchType {
            get {
                return ResourceManager.GetString("serchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待机.
        /// </summary>
        public static string Standby {
            get {
                return ResourceManager.GetString("Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统默认数据，不能删除.
        /// </summary>
        public static string SystemDefaultDataNotDel {
            get {
                return ResourceManager.GetString("SystemDefaultDataNotDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码规则与工装条码.
        /// </summary>
        public static string TooName {
            get {
                return ResourceManager.GetString("TooName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户验证中.
        /// </summary>
        public static string user_yzz {
            get {
                return ResourceManager.GetString("user_yzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请等待.
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待扫工装.
        /// </summary>
        public static string WaittingSacnFixtures {
            get {
                return ResourceManager.GetString("WaittingSacnFixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待扫描条码.
        /// </summary>
        public static string WaittingScanBarcode {
            get {
                return ResourceManager.GetString("WaittingScanBarcode", resourceCulture);
            }
        }
    }
}
