//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesDatas.Language_Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language_English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_English() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MesDatas.Language_Resources.language_English", typeof(language_English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Barcode verification failed 的本地化字符串。
        /// </summary>
        public static string barCode_NG {
            get {
                return ResourceManager.GetString("barCode_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Barcode verification passed 的本地化字符串。
        /// </summary>
        public static string barCode_OK {
            get {
                return ResourceManager.GetString("barCode_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Barcode scanned repeatedly 的本地化字符串。
        /// </summary>
        public static string barCode_repeat {
            get {
                return ResourceManager.GetString("barCode_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No barcode collected 的本地化字符串。
        /// </summary>
        public static string barCode_State {
            get {
                return ResourceManager.GetString("barCode_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start reading data 的本地化字符串。
        /// </summary>
        public static string begin_read_data {
            get {
                return ResourceManager.GetString("begin_read_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check the online parameters 的本地化字符串。
        /// </summary>
        public static string Check_param {
            get {
                return ResourceManager.GetString("Check_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check if the account password is correct 的本地化字符串。
        /// </summary>
        public static string checkIdorpwd {
            get {
                return ResourceManager.GetString("checkIdorpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Name 的本地化字符串。
        /// </summary>
        public static string CName {
            get {
                return ResourceManager.GetString("CName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 password 的本地化字符串。
        /// </summary>
        public static string comboBox2_Items {
            get {
                return ResourceManager.GetString("comboBox2.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 swipe 的本地化字符串。
        /// </summary>
        public static string comboBox2_Items1 {
            get {
                return ResourceManager.GetString("comboBox2.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please continue production 的本地化字符串。
        /// </summary>
        public static string Continue_production {
            get {
                return ResourceManager.GetString("Continue_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product number 的本地化字符串。
        /// </summary>
        public static string d2CPBH {
            get {
                return ResourceManager.GetString("d2CPBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Results 的本地化字符串。
        /// </summary>
        public static string d2CPJG {
            get {
                return ResourceManager.GetString("d2CPJG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product barcode 的本地化字符串。
        /// </summary>
        public static string d2CPTM {
            get {
                return ResourceManager.GetString("d2CPTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test time 的本地化字符串。
        /// </summary>
        public static string d2CSSJ {
            get {
                return ResourceManager.GetString("d2CSSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 operator 的本地化字符串。
        /// </summary>
        public static string d2CZY {
            get {
                return ResourceManager.GetString("d2CZY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NO 的本地化字符串。
        /// </summary>
        public static string d2No {
            get {
                return ResourceManager.GetString("d2No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload status 的本地化字符串。
        /// </summary>
        public static string d2SCZT {
            get {
                return ResourceManager.GetString("d2SCZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add failed 的本地化字符串。
        /// </summary>
        public static string ErrorBtnAdd {
            get {
                return ResourceManager.GetString("ErrorBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete failed 的本地化字符串。
        /// </summary>
        public static string ErrorBtnDelete {
            get {
                return ResourceManager.GetString("ErrorBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save failed 的本地化字符串。
        /// </summary>
        public static string ErrorBtnSave {
            get {
                return ResourceManager.GetString("ErrorBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update failed 的本地化字符串。
        /// </summary>
        public static string ErrorBtnUpdate {
            get {
                return ResourceManager.GetString("ErrorBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixture verification failed 的本地化字符串。
        /// </summary>
        public static string Fixture_NG {
            get {
                return ResourceManager.GetString("Fixture_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixture verification successful 的本地化字符串。
        /// </summary>
        public static string Fixture_OK {
            get {
                return ResourceManager.GetString("Fixture_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formula number 的本地化字符串。
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the production work order number: 的本地化字符串。
        /// </summary>
        public static string InputBox {
            get {
                return ResourceManager.GetString("InputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 time Not inputted (Reminder: Exit the system without entering 3 times) 的本地化字符串。
        /// </summary>
        public static string InputBox1 {
            get {
                return ResourceManager.GetString("InputBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Production work order 的本地化字符串。
        /// </summary>
        public static string InputBoxName {
            get {
                return ResourceManager.GetString("InputBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your account and password 的本地化字符串。
        /// </summary>
        public static string inputTip {
            get {
                return ResourceManager.GetString("inputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standby 的本地化字符串。
        /// </summary>
        public static string label_Value {
            get {
                return ResourceManager.GetString("label_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 on line 的本地化字符串。
        /// </summary>
        public static string loginMode {
            get {
                return ResourceManager.GetString("loginMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 off line 的本地化字符串。
        /// </summary>
        public static string loginMode1 {
            get {
                return ResourceManager.GetString("loginMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status display: The current employee card does not have swipe login permission! 的本地化字符串。
        /// </summary>
        public static string loginType {
            get {
                return ResourceManager.GetString("loginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Logintype1 {
            get {
                return ResourceManager.GetString("Logintype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swipe card 的本地化字符串。
        /// </summary>
        public static string Logintype2 {
            get {
                return ResourceManager.GetString("Logintype2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product code 的本地化字符串。
        /// </summary>
        public static string MateName {
            get {
                return ResourceManager.GetString("MateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material verification failed 的本地化字符串。
        /// </summary>
        public static string material_NG {
            get {
                return ResourceManager.GetString("material_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material verification passed 的本地化字符串。
        /// </summary>
        public static string material_OK {
            get {
                return ResourceManager.GetString("material_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading data to MES 的本地化字符串。
        /// </summary>
        public static string Mes_upload {
            get {
                return ResourceManager.GetString("Mes_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data upload failed 的本地化字符串。
        /// </summary>
        public static string Mes_upload_NG {
            get {
                return ResourceManager.GetString("Mes_upload_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data upload successful 的本地化字符串。
        /// </summary>
        public static string Mes_upload_OK {
            get {
                return ResourceManager.GetString("Mes_upload_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select login mode 的本地化字符串。
        /// </summary>
        public static string ModeTip {
            get {
                return ResourceManager.GetString("ModeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have offline login permission, please select again! 的本地化字符串。
        /// </summary>
        public static string offlineTip {
            get {
                return ResourceManager.GetString("offlineTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User verification failed 的本地化字符串。
        /// </summary>
        public static string onlineUser_NG {
            get {
                return ResourceManager.GetString("onlineUser_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User verification successful 的本地化字符串。
        /// </summary>
        public static string onlineUser_OK {
            get {
                return ResourceManager.GetString("onlineUser_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 operation 的本地化字符串。
        /// </summary>
        public static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully added 的本地化字符串。
        /// </summary>
        public static string PassBtnAdd {
            get {
                return ResourceManager.GetString("PassBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete successful 的本地化字符串。
        /// </summary>
        public static string PassBtnDelete {
            get {
                return ResourceManager.GetString("PassBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save successful 的本地化字符串。
        /// </summary>
        public static string PassBtnSave {
            get {
                return ResourceManager.GetString("PassBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update successful 的本地化字符串。
        /// </summary>
        public static string PassBtnUpdate {
            get {
                return ResourceManager.GetString("PassBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device connection failed, please restart the software or restart the machine! 的本地化字符串。
        /// </summary>
        public static string plcConn {
            get {
                return ResourceManager.GetString("plcConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status display: Port opening failed! 的本地化字符串。
        /// </summary>
        public static string portNG {
            get {
                return ResourceManager.GetString("portNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status display: Port opened successfully! 的本地化字符串。
        /// </summary>
        public static string portOK {
            get {
                return ResourceManager.GetString("portOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status display: Port occupied! 的本地化字符串。
        /// </summary>
        public static string portType {
            get {
                return ResourceManager.GetString("portType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Card reader port and device number acquisition failed, please maintain first! 的本地化字符串。
        /// </summary>
        public static string posType {
            get {
                return ResourceManager.GetString("posType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please upload again 的本地化字符串。
        /// </summary>
        public static string Re_upload {
            get {
                return ResourceManager.GetString("Re_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local data protection 的本地化字符串。
        /// </summary>
        public static string Read_data {
            get {
                return ResourceManager.GetString("Read_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local data protection successful 的本地化字符串。
        /// </summary>
        public static string Read_data_OK {
            get {
                return ResourceManager.GetString("Read_data_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close the card reader 的本地化字符串。
        /// </summary>
        public static string readCard_Close {
            get {
                return ResourceManager.GetString("readCard_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the card reader 的本地化字符串。
        /// </summary>
        public static string readCard_Open {
            get {
                return ResourceManager.GetString("readCard_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status display: Card reading successful! 的本地化字符串。
        /// </summary>
        public static string readCardOK {
            get {
                return ResourceManager.GetString("readCardOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan completed 的本地化字符串。
        /// </summary>
        public static string ScanBarCode_OK {
            get {
                return ResourceManager.GetString("ScanBarCode_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait for scanning code 的本地化字符串。
        /// </summary>
        public static string scanning {
            get {
                return ResourceManager.GetString("scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current card number has multiple accounts and cannot be swiped to log in! 的本地化字符串。
        /// </summary>
        public static string serchType {
            get {
                return ResourceManager.GetString("serchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System default data cannot be deleted 的本地化字符串。
        /// </summary>
        public static string SystemDefaultDataNotDel {
            get {
                return ResourceManager.GetString("SystemDefaultDataNotDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Barcode rules and fixture barcodes 的本地化字符串。
        /// </summary>
        public static string TooName {
            get {
                return ResourceManager.GetString("TooName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User verification in progress 的本地化字符串。
        /// </summary>
        public static string user_yzz {
            get {
                return ResourceManager.GetString("user_yzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single user verification successful 的本地化字符串。
        /// </summary>
        public static string UserCheck {
            get {
                return ResourceManager.GetString("UserCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please stand by 的本地化字符串。
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please scan the fixture 的本地化字符串。
        /// </summary>
        public static string Wait_scan_Jig {
            get {
                return ResourceManager.GetString("Wait_scan_Jig", resourceCulture);
            }
        }
    }
}
