//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesDatas.Language_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language_Chinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_Chinese() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MesDatas.Language_Resources.language_Chinese", typeof(language_Chinese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.btw)|*.btw.
        /// </summary>
        public static string cboFileFormat_TCP_Items {
            get {
                return ResourceManager.GetString("cboFileFormat_TCP.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.prn)|*.prn.
        /// </summary>
        public static string cboFileFormat_TCP_Items1 {
            get {
                return ResourceManager.GetString("cboFileFormat_TCP.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查账号密码是否正确.
        /// </summary>
        public static string checkIdorpwd {
            get {
                return ResourceManager.GetString("checkIdorpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码登录.
        /// </summary>
        public static string comboBox2_Items {
            get {
                return ResourceManager.GetString("comboBox2.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷卡登录.
        /// </summary>
        public static string comboBox2_Items1 {
            get {
                return ResourceManager.GetString("comboBox2.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码.
        /// </summary>
        public static string d1Barcode {
            get {
                return ResourceManager.GetString("d1Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工位.
        /// </summary>
        public static string d1StationName {
            get {
                return ResourceManager.GetString("d1StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品结果.
        /// </summary>
        public static string d2CPJG {
            get {
                return ResourceManager.GetString("d2CPJG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品条码.
        /// </summary>
        public static string d2CPTM {
            get {
                return ResourceManager.GetString("d2CPTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品型号.
        /// </summary>
        public static string d2CPXH {
            get {
                return ResourceManager.GetString("d2CPXH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试时间.
        /// </summary>
        public static string d2CSSJ {
            get {
                return ResourceManager.GetString("d2CSSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作员.
        /// </summary>
        public static string d2CZY {
            get {
                return ResourceManager.GetString("d2CZY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string d2NO {
            get {
                return ResourceManager.GetString("d2NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传状态.
        /// </summary>
        public static string d2SCZT {
            get {
                return ResourceManager.GetString("d2SCZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string d3Name {
            get {
                return ResourceManager.GetString("d3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 值.
        /// </summary>
        public static string d3Value {
            get {
                return ResourceManager.GetString("d3Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标准值.
        /// </summary>
        public static string d4BZZ {
            get {
                return ResourceManager.GetString("d4BZZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试结果.
        /// </summary>
        public static string d4CSJG {
            get {
                return ResourceManager.GetString("d4CSJG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试项目.
        /// </summary>
        public static string d4CSXM {
            get {
                return ResourceManager.GetString("d4CSXM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string d4NO {
            get {
                return ResourceManager.GetString("d4NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实际值.
        /// </summary>
        public static string d4SJZ {
            get {
                return ResourceManager.GetString("d4SJZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上限值.
        /// </summary>
        public static string d4SXZ {
            get {
                return ResourceManager.GetString("d4SXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下限值.
        /// </summary>
        public static string d4XXZ {
            get {
                return ResourceManager.GetString("d4XXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码规则.
        /// </summary>
        public static string d5BarcodeRule {
            get {
                return ResourceManager.GetString("d5BarcodeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工装编号.
        /// </summary>
        public static string d5FixtureID {
            get {
                return ResourceManager.GetString("d5FixtureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配方编号.
        /// </summary>
        public static string d5ID {
            get {
                return ResourceManager.GetString("d5ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品编码.
        /// </summary>
        public static string d5PCode {
            get {
                return ResourceManager.GetString("d5PCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品名称.
        /// </summary>
        public static string d5PName {
            get {
                return ResourceManager.GetString("d5PName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二维条码验证.
        /// </summary>
        public static string d5QRCode {
            get {
                return ResourceManager.GetString("d5QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加失败.
        /// </summary>
        public static string ErrorBtnAdd {
            get {
                return ResourceManager.GetString("ErrorBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败.
        /// </summary>
        public static string ErrorBtnDelete {
            get {
                return ResourceManager.GetString("ErrorBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失败.
        /// </summary>
        public static string ErrorBtnSave {
            get {
                return ResourceManager.GetString("ErrorBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新失败.
        /// </summary>
        public static string ErrorBtnUpdate {
            get {
                return ResourceManager.GetString("ErrorBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入当前工单号：.
        /// </summary>
        public static string InputBox {
            get {
                return ResourceManager.GetString("InputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次未输入（提示：3次未输入退出系统）.
        /// </summary>
        public static string InputBox1 {
            get {
                return ResourceManager.GetString("InputBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产工单号.
        /// </summary>
        public static string InputBoxName {
            get {
                return ResourceManager.GetString("InputBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入账号和密码.
        /// </summary>
        public static string inputTip {
            get {
                return ResourceManager.GetString("inputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线.
        /// </summary>
        public static string loginMode {
            get {
                return ResourceManager.GetString("loginMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 离线.
        /// </summary>
        public static string loginMode1 {
            get {
                return ResourceManager.GetString("loginMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态显示：当前员工卡无刷卡登录权限！.
        /// </summary>
        public static string loginType {
            get {
                return ResourceManager.GetString("loginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string Logintype1 {
            get {
                return ResourceManager.GetString("Logintype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷卡.
        /// </summary>
        public static string Logintype2 {
            get {
                return ResourceManager.GetString("Logintype2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下限.
        /// </summary>
        public static string LowerLimit {
            get {
                return ResourceManager.GetString("LowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择登录模式.
        /// </summary>
        public static string ModeTip {
            get {
                return ResourceManager.GetString("ModeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您没有离线登录权限、请重新选择！.
        /// </summary>
        public static string offlineTip {
            get {
                return ResourceManager.GetString("offlineTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查联机参数.
        /// </summary>
        public static string OT_CheckParam {
            get {
                return ResourceManager.GetString("OT_CheckParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请取下产品继续生产.
        /// </summary>
        public static string OT_Continue {
            get {
                return ResourceManager.GetString("OT_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请重新上传.
        /// </summary>
        public static string OT_Reupload {
            get {
                return ResourceManager.GetString("OT_Reupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫码完成.
        /// </summary>
        public static string OT_Scaned {
            get {
                return ResourceManager.GetString("OT_Scaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待扫工装.
        /// </summary>
        public static string OT_ScanFixture {
            get {
                return ResourceManager.GetString("OT_ScanFixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请继续扫描工装二维码.
        /// </summary>
        public static string OT_ScanFixtureContinue {
            get {
                return ResourceManager.GetString("OT_ScanFixtureContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请开始生产.
        /// </summary>
        public static string OT_StartProduce {
            get {
                return ResourceManager.GetString("OT_StartProduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工位1测试NG, 无法进入工位2.
        /// </summary>
        public static string OT_Station1NG {
            get {
                return ResourceManager.GetString("OT_Station1NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请等待.
        /// </summary>
        public static string OT_Wait {
            get {
                return ResourceManager.GetString("OT_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待扫描条码.
        /// </summary>
        public static string OT_WaitingScan {
            get {
                return ResourceManager.GetString("OT_WaitingScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加成功.
        /// </summary>
        public static string PassBtnAdd {
            get {
                return ResourceManager.GetString("PassBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除成功.
        /// </summary>
        public static string PassBtnDelete {
            get {
                return ResourceManager.GetString("PassBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功.
        /// </summary>
        public static string PassBtnSave {
            get {
                return ResourceManager.GetString("PassBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新成功.
        /// </summary>
        public static string PassBtnUpdate {
            get {
                return ResourceManager.GetString("PassBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC连接失败，请重启软件或重启机台！.
        /// </summary>
        public static string plcConn {
            get {
                return ResourceManager.GetString("plcConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态显示：端口打开失败！.
        /// </summary>
        public static string portNG {
            get {
                return ResourceManager.GetString("portNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态显示：端口打开成功！.
        /// </summary>
        public static string portOK {
            get {
                return ResourceManager.GetString("portOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态显示：端口被占用！.
        /// </summary>
        public static string portType {
            get {
                return ResourceManager.GetString("portType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读卡器端口、设备号获取失败、请先维护！.
        /// </summary>
        public static string posType {
            get {
                return ResourceManager.GetString("posType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭读卡器.
        /// </summary>
        public static string readCard_Close {
            get {
                return ResourceManager.GetString("readCard_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开读卡器.
        /// </summary>
        public static string readCard_Open {
            get {
                return ResourceManager.GetString("readCard_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态显示：读卡成功！.
        /// </summary>
        public static string readCardOK {
            get {
                return ResourceManager.GetString("readCardOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码规则不匹配.
        /// </summary>
        public static string RSBarcode_Dismach {
            get {
                return ResourceManager.GetString("RSBarcode_Dismach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码内容不规范.
        /// </summary>
        public static string RSBarcode_Fault {
            get {
                return ResourceManager.GetString("RSBarcode_Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MES条码校验失败.
        /// </summary>
        public static string RSBarcode_NG {
            get {
                return ResourceManager.GetString("RSBarcode_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无条码验证规则.
        /// </summary>
        public static string RSBarcode_NoRule {
            get {
                return ResourceManager.GetString("RSBarcode_NoRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未获取到条码.
        /// </summary>
        public static string RSBarcode_Null {
            get {
                return ResourceManager.GetString("RSBarcode_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码验证通过.
        /// </summary>
        public static string RSBarcode_OK {
            get {
                return ResourceManager.GetString("RSBarcode_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码重复扫描.
        /// </summary>
        public static string RSBarcode_Repeat {
            get {
                return ResourceManager.GetString("RSBarcode_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地数据保存完成.
        /// </summary>
        public static string RSData_Saved {
            get {
                return ResourceManager.GetString("RSData_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地数据保存中.
        /// </summary>
        public static string RSData_Saving {
            get {
                return ResourceManager.GetString("RSData_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始读取数据.
        /// </summary>
        public static string RSData_StartReading {
            get {
                return ResourceManager.GetString("RSData_StartReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联机数据上传中.
        /// </summary>
        public static string RSData_Uploading {
            get {
                return ResourceManager.GetString("RSData_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联机数据上传失败.
        /// </summary>
        public static string RSData_UploadNG {
            get {
                return ResourceManager.GetString("RSData_UploadNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联机数据上传成功.
        /// </summary>
        public static string RSData_UploadOK {
            get {
                return ResourceManager.GetString("RSData_UploadOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工装编号验证失败.
        /// </summary>
        public static string RSFixture_NG {
            get {
                return ResourceManager.GetString("RSFixture_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无需工装验证.
        /// </summary>
        public static string RSFixture_NotRequire {
            get {
                return ResourceManager.GetString("RSFixture_NotRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工装编号验证通过.
        /// </summary>
        public static string RSFixture_OK {
            get {
                return ResourceManager.GetString("RSFixture_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要工装验证.
        /// </summary>
        public static string RSFixture_RequireValidate {
            get {
                return ResourceManager.GetString("RSFixture_RequireValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工装验证中.
        /// </summary>
        public static string RSFixture_Validating {
            get {
                return ResourceManager.GetString("RSFixture_Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物料验证失败.
        /// </summary>
        public static string RSMaterial_NG {
            get {
                return ResourceManager.GetString("RSMaterial_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物料验证通过.
        /// </summary>
        public static string RSMaterial_OK {
            get {
                return ResourceManager.GetString("RSMaterial_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工位1无此条码数据.
        /// </summary>
        public static string RSStation_NoData {
            get {
                return ResourceManager.GetString("RSStation_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工位1测试结果为NG.
        /// </summary>
        public static string RSStation_Station1NG {
            get {
                return ResourceManager.GetString("RSStation_Station1NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先在工位1完成测试.
        /// </summary>
        public static string RSStation_TobeCompleted {
            get {
                return ResourceManager.GetString("RSStation_TobeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单机用户验证成功.
        /// </summary>
        public static string RSUser_OfflineOK {
            get {
                return ResourceManager.GetString("RSUser_OfflineOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联机用户验证失败.
        /// </summary>
        public static string RSUser_OnlineNG {
            get {
                return ResourceManager.GetString("RSUser_OnlineNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联机用户验证成功.
        /// </summary>
        public static string RSUser_OnlineOK {
            get {
                return ResourceManager.GetString("RSUser_OnlineOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户验证中.
        /// </summary>
        public static string RSUser_Verifing {
            get {
                return ResourceManager.GetString("RSUser_Verifing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前卡号存在多个账户、不能刷卡登录！.
        /// </summary>
        public static string serchType {
            get {
                return ResourceManager.GetString("serchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待机.
        /// </summary>
        public static string Standby {
            get {
                return ResourceManager.GetString("Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统默认数据，不能删除.
        /// </summary>
        public static string SystemDefaultDataNotDel {
            get {
                return ResourceManager.GetString("SystemDefaultDataNotDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果.
        /// </summary>
        public static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败.
        /// </summary>
        public static string UploadState_Failed {
            get {
                return ResourceManager.GetString("UploadState_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地.
        /// </summary>
        public static string UploadState_Local {
            get {
                return ResourceManager.GetString("UploadState_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        public static string UploadState_Success {
            get {
                return ResourceManager.GetString("UploadState_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上限.
        /// </summary>
        public static string UpperLimit {
            get {
                return ResourceManager.GetString("UpperLimit", resourceCulture);
            }
        }
    }
}
