//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesDatas.Language_Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language_Chinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_Chinese() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MesDatas.Language_Resources.language_Chinese", typeof(language_Chinese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 条码校验失败 的本地化字符串。
        /// </summary>
        public static string barCode_NG {
            get {
                return ResourceManager.GetString("barCode_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码校验通过 的本地化字符串。
        /// </summary>
        public static string barCode_OK {
            get {
                return ResourceManager.GetString("barCode_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码重复扫描 的本地化字符串。
        /// </summary>
        public static string barCode_repeat {
            get {
                return ResourceManager.GetString("barCode_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未获取到条码，请重新扫描！ 的本地化字符串。
        /// </summary>
        public static string barCode_State {
            get {
                return ResourceManager.GetString("barCode_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始读取数据 的本地化字符串。
        /// </summary>
        public static string begin_read_data {
            get {
                return ResourceManager.GetString("begin_read_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查联机参数 的本地化字符串。
        /// </summary>
        public static string Check_param {
            get {
                return ResourceManager.GetString("Check_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查账号密码是否正确 的本地化字符串。
        /// </summary>
        public static string checkIdorpwd {
            get {
                return ResourceManager.GetString("checkIdorpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称 的本地化字符串。
        /// </summary>
        public static string CName {
            get {
                return ResourceManager.GetString("CName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码登录 的本地化字符串。
        /// </summary>
        public static string comboBox2_Items {
            get {
                return ResourceManager.GetString("comboBox2.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷卡登录 的本地化字符串。
        /// </summary>
        public static string comboBox2_Items1 {
            get {
                return ResourceManager.GetString("comboBox2.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请取下产品继续生产 的本地化字符串。
        /// </summary>
        public static string Continue_production {
            get {
                return ResourceManager.GetString("Continue_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编号 的本地化字符串。
        /// </summary>
        public static string d2CPBH {
            get {
                return ResourceManager.GetString("d2CPBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品结果 的本地化字符串。
        /// </summary>
        public static string d2CPJG {
            get {
                return ResourceManager.GetString("d2CPJG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品条码 的本地化字符串。
        /// </summary>
        public static string d2CPTM {
            get {
                return ResourceManager.GetString("d2CPTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试时间 的本地化字符串。
        /// </summary>
        public static string d2CSSJ {
            get {
                return ResourceManager.GetString("d2CSSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员 的本地化字符串。
        /// </summary>
        public static string d2CZY {
            get {
                return ResourceManager.GetString("d2CZY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string d2No {
            get {
                return ResourceManager.GetString("d2No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传状态 的本地化字符串。
        /// </summary>
        public static string d2SCZT {
            get {
                return ResourceManager.GetString("d2SCZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败 的本地化字符串。
        /// </summary>
        public static string ErrorBtnAdd {
            get {
                return ResourceManager.GetString("ErrorBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        public static string ErrorBtnDelete {
            get {
                return ResourceManager.GetString("ErrorBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        public static string ErrorBtnSave {
            get {
                return ResourceManager.GetString("ErrorBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败 的本地化字符串。
        /// </summary>
        public static string ErrorBtnUpdate {
            get {
                return ResourceManager.GetString("ErrorBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工装编号验证失败 的本地化字符串。
        /// </summary>
        public static string Fixture_NG {
            get {
                return ResourceManager.GetString("Fixture_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工装编号验证通过 的本地化字符串。
        /// </summary>
        public static string Fixture_OK {
            get {
                return ResourceManager.GetString("Fixture_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配方编号 的本地化字符串。
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入生产工单号: 的本地化字符串。
        /// </summary>
        public static string InputBox {
            get {
                return ResourceManager.GetString("InputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次未输入(提示：3次未输入退出系统) 的本地化字符串。
        /// </summary>
        public static string InputBox1 {
            get {
                return ResourceManager.GetString("InputBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产工单号 的本地化字符串。
        /// </summary>
        public static string InputBoxName {
            get {
                return ResourceManager.GetString("InputBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入账号和密码 的本地化字符串。
        /// </summary>
        public static string inputTip {
            get {
                return ResourceManager.GetString("inputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待机 的本地化字符串。
        /// </summary>
        public static string label_Value {
            get {
                return ResourceManager.GetString("label_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 的本地化字符串。
        /// </summary>
        public static string loginMode {
            get {
                return ResourceManager.GetString("loginMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        public static string loginMode1 {
            get {
                return ResourceManager.GetString("loginMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态显示：当前员工卡无刷卡登录权限！ 的本地化字符串。
        /// </summary>
        public static string loginType {
            get {
                return ResourceManager.GetString("loginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Logintype1 {
            get {
                return ResourceManager.GetString("Logintype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷卡 的本地化字符串。
        /// </summary>
        public static string Logintype2 {
            get {
                return ResourceManager.GetString("Logintype2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编码 的本地化字符串。
        /// </summary>
        public static string MateName {
            get {
                return ResourceManager.GetString("MateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料验证失败，请重新扫描！ 的本地化字符串。
        /// </summary>
        public static string material_NG {
            get {
                return ResourceManager.GetString("material_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料验证通过 的本地化字符串。
        /// </summary>
        public static string material_OK {
            get {
                return ResourceManager.GetString("material_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联机数据上传中 的本地化字符串。
        /// </summary>
        public static string Mes_upload {
            get {
                return ResourceManager.GetString("Mes_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联机数据上传失败 的本地化字符串。
        /// </summary>
        public static string Mes_upload_NG {
            get {
                return ResourceManager.GetString("Mes_upload_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联机数据上传成功 的本地化字符串。
        /// </summary>
        public static string Mes_upload_OK {
            get {
                return ResourceManager.GetString("Mes_upload_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择登录模式 的本地化字符串。
        /// </summary>
        public static string ModeTip {
            get {
                return ResourceManager.GetString("ModeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有离线登录权限、请重新选择！ 的本地化字符串。
        /// </summary>
        public static string offlineTip {
            get {
                return ResourceManager.GetString("offlineTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联机用户验证失败 的本地化字符串。
        /// </summary>
        public static string onlineUser_NG {
            get {
                return ResourceManager.GetString("onlineUser_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联机用户验证成功 的本地化字符串。
        /// </summary>
        public static string onlineUser_OK {
            get {
                return ResourceManager.GetString("onlineUser_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功 的本地化字符串。
        /// </summary>
        public static string PassBtnAdd {
            get {
                return ResourceManager.GetString("PassBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string PassBtnDelete {
            get {
                return ResourceManager.GetString("PassBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string PassBtnSave {
            get {
                return ResourceManager.GetString("PassBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功 的本地化字符串。
        /// </summary>
        public static string PassBtnUpdate {
            get {
                return ResourceManager.GetString("PassBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC连接失败，请重启软件或重启机台！ 的本地化字符串。
        /// </summary>
        public static string plcConn {
            get {
                return ResourceManager.GetString("plcConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态显示：端口打开失败！ 的本地化字符串。
        /// </summary>
        public static string portNG {
            get {
                return ResourceManager.GetString("portNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态显示：端口打开成功！ 的本地化字符串。
        /// </summary>
        public static string portOK {
            get {
                return ResourceManager.GetString("portOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态显示：端口被占用！ 的本地化字符串。
        /// </summary>
        public static string portType {
            get {
                return ResourceManager.GetString("portType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读卡器端口、设备号获取失败、请先维护！ 的本地化字符串。
        /// </summary>
        public static string posType {
            get {
                return ResourceManager.GetString("posType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请重新上传 的本地化字符串。
        /// </summary>
        public static string Re_upload {
            get {
                return ResourceManager.GetString("Re_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地数据保存中 的本地化字符串。
        /// </summary>
        public static string Read_data {
            get {
                return ResourceManager.GetString("Read_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地数据保存完成 的本地化字符串。
        /// </summary>
        public static string Read_data_OK {
            get {
                return ResourceManager.GetString("Read_data_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭读卡器 的本地化字符串。
        /// </summary>
        public static string readCard_Close {
            get {
                return ResourceManager.GetString("readCard_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开读卡器 的本地化字符串。
        /// </summary>
        public static string readCard_Open {
            get {
                return ResourceManager.GetString("readCard_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态显示：读卡成功！ 的本地化字符串。
        /// </summary>
        public static string readCardOK {
            get {
                return ResourceManager.GetString("readCardOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫码完成 的本地化字符串。
        /// </summary>
        public static string ScanBarCode_OK {
            get {
                return ResourceManager.GetString("ScanBarCode_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待扫描条码 的本地化字符串。
        /// </summary>
        public static string scanning {
            get {
                return ResourceManager.GetString("scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前卡号存在多个账户、不能刷卡登录！ 的本地化字符串。
        /// </summary>
        public static string serchType {
            get {
                return ResourceManager.GetString("serchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统默认数据，不能删除 的本地化字符串。
        /// </summary>
        public static string SystemDefaultDataNotDel {
            get {
                return ResourceManager.GetString("SystemDefaultDataNotDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码规则与工装条码 的本地化字符串。
        /// </summary>
        public static string TooName {
            get {
                return ResourceManager.GetString("TooName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户验证中 的本地化字符串。
        /// </summary>
        public static string user_yzz {
            get {
                return ResourceManager.GetString("user_yzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单机用户验证成功 的本地化字符串。
        /// </summary>
        public static string UserCheck {
            get {
                return ResourceManager.GetString("UserCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请等待 的本地化字符串。
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待扫工装 的本地化字符串。
        /// </summary>
        public static string Wait_scan_Jig {
            get {
                return ResourceManager.GetString("Wait_scan_Jig", resourceCulture);
            }
        }
    }
}
