//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesDatas.Language_Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language_Thai {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_Thai() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MesDatas.Language_Resources.language_Thai", typeof(language_Thai).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 การตรวจสอบบาร์โค้ดล้มเหลว 的本地化字符串。
        /// </summary>
        public static string barCode_NG {
            get {
                return ResourceManager.GetString("barCode_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การตรวจสอบบาร์โค้ด ผ่าน 的本地化字符串。
        /// </summary>
        public static string barCode_OK {
            get {
                return ResourceManager.GetString("barCode_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 บาร์โค้ดกวาดซ้ำ 的本地化字符串。
        /// </summary>
        public static string barCode_repeat {
            get {
                return ResourceManager.GetString("barCode_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ไม่มีบาร์โค้ด 的本地化字符串。
        /// </summary>
        public static string barCode_State {
            get {
                return ResourceManager.GetString("barCode_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 เริ่มอ่านข้อมูล 的本地化字符串。
        /// </summary>
        public static string begin_read_data {
            get {
                return ResourceManager.GetString("begin_read_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 โปรดตรวจสอบพารามิเตอร์ออนไลน์ 的本地化字符串。
        /// </summary>
        public static string Check_param {
            get {
                return ResourceManager.GetString("Check_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 โปรดตรวจสอบรหัสผ่านหมายเลขบัญชีว่าถูกต้องหรือไม่ 的本地化字符串。
        /// </summary>
        public static string checkIdorpwd {
            get {
                return ResourceManager.GetString("checkIdorpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ชื่อผลิตภัณฑ์ 的本地化字符串。
        /// </summary>
        public static string CName {
            get {
                return ResourceManager.GetString("CName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 รหัสผ่าน 的本地化字符串。
        /// </summary>
        public static string comboBox2_Items {
            get {
                return ResourceManager.GetString("comboBox2.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 รูดบัตร 的本地化字符串。
        /// </summary>
        public static string comboBox2_Items1 {
            get {
                return ResourceManager.GetString("comboBox2.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 โปรดผลิตต่อไป 的本地化字符串。
        /// </summary>
        public static string Continue_production {
            get {
                return ResourceManager.GetString("Continue_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 หมายเลขสินค้า 的本地化字符串。
        /// </summary>
        public static string d2CPBH {
            get {
                return ResourceManager.GetString("d2CPBH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ผลลัพธ์ของผลิตภัณฑ์ 的本地化字符串。
        /// </summary>
        public static string d2CPJG {
            get {
                return ResourceManager.GetString("d2CPJG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 บาร์โค้ดผลิตภัณฑ์ 的本地化字符串。
        /// </summary>
        public static string d2CPTM {
            get {
                return ResourceManager.GetString("d2CPTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 เวลาทดสอบ 的本地化字符串。
        /// </summary>
        public static string d2CSSJ {
            get {
                return ResourceManager.GetString("d2CSSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ผู้ประกอบการ 的本地化字符串。
        /// </summary>
        public static string d2CZY {
            get {
                return ResourceManager.GetString("d2CZY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NO 的本地化字符串。
        /// </summary>
        public static string d2No {
            get {
                return ResourceManager.GetString("d2No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 สถานะการอัปโหลด 的本地化字符串。
        /// </summary>
        public static string d2SCZT {
            get {
                return ResourceManager.GetString("d2SCZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ลบ 的本地化字符串。
        /// </summary>
        public static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 เพิ่มล้มเหลว 的本地化字符串。
        /// </summary>
        public static string ErrorBtnAdd {
            get {
                return ResourceManager.GetString("ErrorBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การลบล้มเหลว 的本地化字符串。
        /// </summary>
        public static string ErrorBtnDelete {
            get {
                return ResourceManager.GetString("ErrorBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 บันทึกล้มเหลว 的本地化字符串。
        /// </summary>
        public static string ErrorBtnSave {
            get {
                return ResourceManager.GetString("ErrorBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การอัปเดตล้มเหลว 的本地化字符串。
        /// </summary>
        public static string ErrorBtnUpdate {
            get {
                return ResourceManager.GetString("ErrorBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การตรวจสอบเครื่องมือแก้ไขล้มเหลว 的本地化字符串。
        /// </summary>
        public static string Fixture_NG {
            get {
                return ResourceManager.GetString("Fixture_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การตรวจสอบการรักษาประสบความสำเร็จ 的本地化字符串。
        /// </summary>
        public static string Fixture_OK {
            get {
                return ResourceManager.GetString("Fixture_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 หมายเลขสูตร 的本地化字符串。
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 โปรดป้อนหมายเลขการผลิต: 的本地化字符串。
        /// </summary>
        public static string InputBox {
            get {
                return ResourceManager.GetString("InputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ครั้ง ไม่แพ้ไม่ป้อน (เคล็ดลับ: 3 ครั้งที่ไม่ป้อนออกจากระบบ) 的本地化字符串。
        /// </summary>
        public static string InputBox1 {
            get {
                return ResourceManager.GetString("InputBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ใบสั่งงานผลิต 的本地化字符串。
        /// </summary>
        public static string InputBoxName {
            get {
                return ResourceManager.GetString("InputBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 กรุณากรอกหมายเลขบัญชีและรหัสผ่าน 的本地化字符串。
        /// </summary>
        public static string inputTip {
            get {
                return ResourceManager.GetString("inputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 สแตนด์บาย 的本地化字符串。
        /// </summary>
        public static string label_Value {
            get {
                return ResourceManager.GetString("label_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ออนไลน์ 的本地化字符串。
        /// </summary>
        public static string loginMode {
            get {
                return ResourceManager.GetString("loginMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ออฟไลน์ 的本地化字符串。
        /// </summary>
        public static string loginMode1 {
            get {
                return ResourceManager.GetString("loginMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 แสดงสถานะ: บัตรพนักงานปัจจุบันสิทธิ์การเข้าสู่ระบบแบบไม่มีรูด! 的本地化字符串。
        /// </summary>
        public static string loginType {
            get {
                return ResourceManager.GetString("loginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 รหัสผ่าน 的本地化字符串。
        /// </summary>
        public static string Logintype1 {
            get {
                return ResourceManager.GetString("Logintype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 รูดบัตร 的本地化字符串。
        /// </summary>
        public static string Logintype2 {
            get {
                return ResourceManager.GetString("Logintype2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 รหัสผลิตภัณฑ์ 的本地化字符串。
        /// </summary>
        public static string MateName {
            get {
                return ResourceManager.GetString("MateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การตรวจสอบวัสดุล้มเหลว 的本地化字符串。
        /// </summary>
        public static string material_NG {
            get {
                return ResourceManager.GetString("material_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การตรวจสอบวัสดุที่ประสบความสำเร็จ 的本地化字符串。
        /// </summary>
        public static string material_OK {
            get {
                return ResourceManager.GetString("material_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การอัปโหลดข้อมูลใน MES 的本地化字符串。
        /// </summary>
        public static string Mes_upload {
            get {
                return ResourceManager.GetString("Mes_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การอัพโหลดข้อมูลล้มเหลว 的本地化字符串。
        /// </summary>
        public static string Mes_upload_NG {
            get {
                return ResourceManager.GetString("Mes_upload_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การอัพโหลดข้อมูลสำเร็จ 的本地化字符串。
        /// </summary>
        public static string Mes_upload_OK {
            get {
                return ResourceManager.GetString("Mes_upload_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 โปรดเลือกโหมดการเข้าสู่ระบบ 的本地化字符串。
        /// </summary>
        public static string ModeTip {
            get {
                return ResourceManager.GetString("ModeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 คุณไม่มีสิทธิ์เข้าสู่ระบบแบบออฟไลน์โปรดเลือกใหม่! 的本地化字符串。
        /// </summary>
        public static string offlineTip {
            get {
                return ResourceManager.GetString("offlineTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การตรวจสอบผู้ใช้ล้มเหลว 的本地化字符串。
        /// </summary>
        public static string onlineUser_NG {
            get {
                return ResourceManager.GetString("onlineUser_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การตรวจสอบผู้ใช้สำเร็จ 的本地化字符串。
        /// </summary>
        public static string onlineUser_OK {
            get {
                return ResourceManager.GetString("onlineUser_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การดำเนินงาน 的本地化字符串。
        /// </summary>
        public static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 เพิ่มความสำเร็จ 的本地化字符串。
        /// </summary>
        public static string PassBtnAdd {
            get {
                return ResourceManager.GetString("PassBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ลบสำเร็จ 的本地化字符串。
        /// </summary>
        public static string PassBtnDelete {
            get {
                return ResourceManager.GetString("PassBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 บันทึกความสำเร็จ 的本地化字符串。
        /// </summary>
        public static string PassBtnSave {
            get {
                return ResourceManager.GetString("PassBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 อัพเดทสำเร็จ 的本地化字符串。
        /// </summary>
        public static string PassBtnUpdate {
            get {
                return ResourceManager.GetString("PassBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การเชื่อมต่ออุปกรณ์ล้มเหลวโปรดรีสตาร์ทซอฟต์แวร์หรือรีสตาร์ทโต๊ะ! 的本地化字符串。
        /// </summary>
        public static string plcConn {
            get {
                return ResourceManager.GetString("plcConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 แสดงสถานะ: พอร์ตเปิดล้มเหลว! 的本地化字符串。
        /// </summary>
        public static string portNG {
            get {
                return ResourceManager.GetString("portNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 แสดงสถานะ: พอร์ตเปิดสำเร็จ! 的本地化字符串。
        /// </summary>
        public static string portOK {
            get {
                return ResourceManager.GetString("portOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 แสดงสถานะ: พอร์ตถูกครอบครอง! 的本地化字符串。
        /// </summary>
        public static string portType {
            get {
                return ResourceManager.GetString("portType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 พอร์ตเครื่องอ่านบัตรและหมายเลขอุปกรณ์ไม่ได้รับล้มเหลวโปรดบำรุงรักษาก่อน! 的本地化字符串。
        /// </summary>
        public static string posType {
            get {
                return ResourceManager.GetString("posType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 กรุณาอัพโหลดใหม่ 的本地化字符串。
        /// </summary>
        public static string Re_upload {
            get {
                return ResourceManager.GetString("Re_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ในการประกันข้อมูลท้องถิ่น 的本地化字符串。
        /// </summary>
        public static string Read_data {
            get {
                return ResourceManager.GetString("Read_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ความสำเร็จของการประกันข้อมูลในพื้นที่ 的本地化字符串。
        /// </summary>
        public static string Read_data_OK {
            get {
                return ResourceManager.GetString("Read_data_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ปิดเครื่องอ่านบัตร 的本地化字符串。
        /// </summary>
        public static string readCard_Close {
            get {
                return ResourceManager.GetString("readCard_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 เปิดเครื่องอ่านบัตร 的本地化字符串。
        /// </summary>
        public static string readCard_Open {
            get {
                return ResourceManager.GetString("readCard_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 แสดงสถานะ: อ่านการ์ดสำเร็จ! 的本地化字符串。
        /// </summary>
        public static string readCardOK {
            get {
                return ResourceManager.GetString("readCardOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 บันทึก 的本地化字符串。
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 สแกนโค้ดเสร็จสมบูรณ์ 的本地化字符串。
        /// </summary>
        public static string ScanBarCode_OK {
            get {
                return ResourceManager.GetString("ScanBarCode_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 รอสแกนรหัส 的本地化字符串。
        /// </summary>
        public static string scanning {
            get {
                return ResourceManager.GetString("scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 หมายเลขบัตรปัจจุบัน มีหลายบัญชีและไม่สามารถเข้าสู่ระบบด้วยบัตรรูด! 的本地化字符串。
        /// </summary>
        public static string serchType {
            get {
                return ResourceManager.GetString("serchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ข้อมูลเริ่มต้นของระบบไม่สามารถลบได้ 的本地化字符串。
        /// </summary>
        public static string SystemDefaultDataNotDel {
            get {
                return ResourceManager.GetString("SystemDefaultDataNotDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 กฎบาร์โค้ดและบาร์โค้ดเครื่องมือ 的本地化字符串。
        /// </summary>
        public static string TooName {
            get {
                return ResourceManager.GetString("TooName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ในการตรวจสอบผู้ใช้ 的本地化字符串。
        /// </summary>
        public static string user_yzz {
            get {
                return ResourceManager.GetString("user_yzz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 การตรวจสอบผู้ใช้แบบสแตนด์อโลนสำเร็จแล้ว 的本地化字符串。
        /// </summary>
        public static string UserCheck {
            get {
                return ResourceManager.GetString("UserCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 กรุณารอ 的本地化字符串。
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 กรุณาสแกนการรักษา 的本地化字符串。
        /// </summary>
        public static string Wait_scan_Jig {
            get {
                return ResourceManager.GetString("Wait_scan_Jig", resourceCulture);
            }
        }
    }
}
