//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesDatas.Language_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language_Thai {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_Thai() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MesDatas.Language_Resources.language_Thai", typeof(language_Thai).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดตรวจสอบพารามิเตอร์ออนไลน์.
        /// </summary>
        public static string Check_param {
            get {
                return ResourceManager.GetString("Check_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดตรวจสอบรหัสผ่านหมายเลขบัญชีว่าถูกต้องหรือไม่.
        /// </summary>
        public static string checkIdorpwd {
            get {
                return ResourceManager.GetString("checkIdorpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่าน.
        /// </summary>
        public static string comboBox2_Items {
            get {
                return ResourceManager.GetString("comboBox2.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูดบัตร.
        /// </summary>
        public static string comboBox2_Items1 {
            get {
                return ResourceManager.GetString("comboBox2.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดผลิตต่อไป.
        /// </summary>
        public static string Continue_production {
            get {
                return ResourceManager.GetString("Continue_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บาร์โค้ด.
        /// </summary>
        public static string d1Barcode {
            get {
                return ResourceManager.GetString("d1Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสถานี.
        /// </summary>
        public static string d1StationName {
            get {
                return ResourceManager.GetString("d1StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผลลัพธ์.
        /// </summary>
        public static string d2CPJG {
            get {
                return ResourceManager.GetString("d2CPJG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บาร์โค้ด.
        /// </summary>
        public static string d2CPTM {
            get {
                return ResourceManager.GetString("d2CPTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสสินค้า.
        /// </summary>
        public static string d2CPXH {
            get {
                return ResourceManager.GetString("d2CPXH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาทดสอบ.
        /// </summary>
        public static string d2CSSJ {
            get {
                return ResourceManager.GetString("d2CSSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ปฏิบัติงาน.
        /// </summary>
        public static string d2CZY {
            get {
                return ResourceManager.GetString("d2CZY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับ.
        /// </summary>
        public static string d2NO {
            get {
                return ResourceManager.GetString("d2NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ.
        /// </summary>
        public static string d2SCZT {
            get {
                return ResourceManager.GetString("d2SCZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string d3Name {
            get {
                return ResourceManager.GetString("d3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่า.
        /// </summary>
        public static string d3Value {
            get {
                return ResourceManager.GetString("d3Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่ามาตรฐาน.
        /// </summary>
        public static string d4BZZ {
            get {
                return ResourceManager.GetString("d4BZZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผลทดสอบ.
        /// </summary>
        public static string d4CSJG {
            get {
                return ResourceManager.GetString("d4CSJG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการทดสอบ.
        /// </summary>
        public static string d4CSXM {
            get {
                return ResourceManager.GetString("d4CSXM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับ.
        /// </summary>
        public static string d4NO {
            get {
                return ResourceManager.GetString("d4NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าที่วัดได้.
        /// </summary>
        public static string d4SJZ {
            get {
                return ResourceManager.GetString("d4SJZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าสูงสุด.
        /// </summary>
        public static string d4SXZ {
            get {
                return ResourceManager.GetString("d4SXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าต่ำสุด.
        /// </summary>
        public static string d4XXZ {
            get {
                return ResourceManager.GetString("d4XXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กฎบาร์โค้ดและบาร์โค้ดเครื่องมือ.
        /// </summary>
        public static string d5BarcodeRule {
            get {
                return ResourceManager.GetString("d5BarcodeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสอุปกรณ์.
        /// </summary>
        public static string d5FixtureID {
            get {
                return ResourceManager.GetString("d5FixtureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขสูตร.
        /// </summary>
        public static string d5ID {
            get {
                return ResourceManager.GetString("d5ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผลิตภัณฑ์.
        /// </summary>
        public static string d5PCode {
            get {
                return ResourceManager.GetString("d5PCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผลิตภัณฑ์.
        /// </summary>
        public static string d5PName {
            get {
                return ResourceManager.GetString("d5PName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การตรวจสอบคิวอาร์โค้ด.
        /// </summary>
        public static string d5QRCode {
            get {
                return ResourceManager.GetString("d5QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบ.
        /// </summary>
        public static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加失败/Add Failed/เพิ่มไม่สำเร็จ.
        /// </summary>
        public static string ErrorBtnAdd {
            get {
                return ResourceManager.GetString("ErrorBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败/Delete Failed/ลบไม่สำเร็จ.
        /// </summary>
        public static string ErrorBtnDelete {
            get {
                return ResourceManager.GetString("ErrorBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失败/Save Failed/บันทึกไม่สำเร็จ.
        /// </summary>
        public static string ErrorBtnSave {
            get {
                return ResourceManager.GetString("ErrorBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新失败/Update Failed/อัปเดตไม่สำเร็จ.
        /// </summary>
        public static string ErrorBtnUpdate {
            get {
                return ResourceManager.GetString("ErrorBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาป้อนใบสั่งงานปัจจุบัน:.
        /// </summary>
        public static string InputBox {
            get {
                return ResourceManager.GetString("InputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องป้อนข้อมูล (คำเตือน: จะออกจากระบบหากไม่ป้อน 3 ครั้ง).
        /// </summary>
        public static string InputBox1 {
            get {
                return ResourceManager.GetString("InputBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบสั่งผลิต.
        /// </summary>
        public static string InputBoxName {
            get {
                return ResourceManager.GetString("InputBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกหมายเลขบัญชีและรหัสผ่าน.
        /// </summary>
        public static string inputTip {
            get {
                return ResourceManager.GetString("inputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออนไลน์.
        /// </summary>
        public static string loginMode {
            get {
                return ResourceManager.GetString("loginMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออฟไลน์.
        /// </summary>
        public static string loginMode1 {
            get {
                return ResourceManager.GetString("loginMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงสถานะ: บัตรพนักงานปัจจุบันสิทธิ์การเข้าสู่ระบบแบบไม่มีรูด!.
        /// </summary>
        public static string loginType {
            get {
                return ResourceManager.GetString("loginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่าน.
        /// </summary>
        public static string Logintype1 {
            get {
                return ResourceManager.GetString("Logintype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูดบัตร.
        /// </summary>
        public static string Logintype2 {
            get {
                return ResourceManager.GetString("Logintype2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขีดจำกัดล่าง.
        /// </summary>
        public static string LowerLimit {
            get {
                return ResourceManager.GetString("LowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดเลือกโหมดการเข้าสู่ระบบ.
        /// </summary>
        public static string ModeTip {
            get {
                return ResourceManager.GetString("ModeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณไม่มีสิทธิ์เข้าสู่ระบบแบบออฟไลน์โปรดเลือกใหม่!.
        /// </summary>
        public static string offlineTip {
            get {
                return ResourceManager.GetString("offlineTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การดำเนินงาน.
        /// </summary>
        public static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาตรวจสอบพารามิเตอร์.
        /// </summary>
        public static string OT_CheckParam {
            get {
                return ResourceManager.GetString("OT_CheckParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำสินค้าออกเพื่อผลิตต่อ.
        /// </summary>
        public static string OT_Continue {
            get {
                return ResourceManager.GetString("OT_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาอัปโหลดใหม่.
        /// </summary>
        public static string OT_Reupload {
            get {
                return ResourceManager.GetString("OT_Reupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สแกนเรียบร้อย.
        /// </summary>
        public static string OT_Scaned {
            get {
                return ResourceManager.GetString("OT_Scaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รอสแกนอุปกรณ์.
        /// </summary>
        public static string OT_ScanFixture {
            get {
                return ResourceManager.GetString("OT_ScanFixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาสแกน QR Code ของอุปกรณ์ต่อไป.
        /// </summary>
        public static string OT_ScanFixtureContinue {
            get {
                return ResourceManager.GetString("OT_ScanFixtureContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเริ่มการผลิต.
        /// </summary>
        public static string OT_StartProduce {
            get {
                return ResourceManager.GetString("OT_StartProduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานีที่ 1 ผลเป็น NG จึงเข้าสถานีที่ 2 ไม่ได้.
        /// </summary>
        public static string OT_Station1NG {
            get {
                return ResourceManager.GetString("OT_Station1NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณารอสักครู่.
        /// </summary>
        public static string OT_Wait {
            get {
                return ResourceManager.GetString("OT_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รอสแกนบาร์โค้ด.
        /// </summary>
        public static string OT_WaitingScan {
            get {
                return ResourceManager.GetString("OT_WaitingScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加成功/Add Successful/เพิ่มสำเร็จ.
        /// </summary>
        public static string PassBtnAdd {
            get {
                return ResourceManager.GetString("PassBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除成功/Delete Successful/ลบสำเร็จ.
        /// </summary>
        public static string PassBtnDelete {
            get {
                return ResourceManager.GetString("PassBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功/Save Successful/บันทึกสำเร็จ.
        /// </summary>
        public static string PassBtnSave {
            get {
                return ResourceManager.GetString("PassBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新成功/Update Successful/อัปเดตสำเร็จ.
        /// </summary>
        public static string PassBtnUpdate {
            get {
                return ResourceManager.GetString("PassBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การเชื่อมต่ออุปกรณ์ล้มเหลวโปรดรีสตาร์ทซอฟต์แวร์หรือรีสตาร์ทโต๊ะ!.
        /// </summary>
        public static string plcConn {
            get {
                return ResourceManager.GetString("plcConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงสถานะ: พอร์ตเปิดล้มเหลว!.
        /// </summary>
        public static string portNG {
            get {
                return ResourceManager.GetString("portNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงสถานะ: พอร์ตเปิดสำเร็จ!.
        /// </summary>
        public static string portOK {
            get {
                return ResourceManager.GetString("portOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงสถานะ: พอร์ตถูกครอบครอง!.
        /// </summary>
        public static string portType {
            get {
                return ResourceManager.GetString("portType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พอร์ตเครื่องอ่านบัตรและหมายเลขอุปกรณ์ไม่ได้รับล้มเหลวโปรดบำรุงรักษาก่อน!.
        /// </summary>
        public static string posType {
            get {
                return ResourceManager.GetString("posType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาอัพโหลดใหม่.
        /// </summary>
        public static string Re_upload {
            get {
                return ResourceManager.GetString("Re_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปิดเครื่องอ่านบัตร.
        /// </summary>
        public static string readCard_Close {
            get {
                return ResourceManager.GetString("readCard_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปิดเครื่องอ่านบัตร.
        /// </summary>
        public static string readCard_Open {
            get {
                return ResourceManager.GetString("readCard_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงสถานะ: อ่านการ์ดสำเร็จ!.
        /// </summary>
        public static string readCardOK {
            get {
                return ResourceManager.GetString("readCardOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กฎบาร์โค้ดไม่ตรงกัน.
        /// </summary>
        public static string RSBarcode_Dismach {
            get {
                return ResourceManager.GetString("RSBarcode_Dismach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบบาร์โค้ดไม่ถูกต้อง.
        /// </summary>
        public static string RSBarcode_Fault {
            get {
                return ResourceManager.GetString("RSBarcode_Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบบาร์โค้ด (MES) ไม่สำเร็จ.
        /// </summary>
        public static string RSBarcode_NG {
            get {
                return ResourceManager.GetString("RSBarcode_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีกฎตรวจสอบบาร์โค้ด.
        /// </summary>
        public static string RSBarcode_NoRule {
            get {
                return ResourceManager.GetString("RSBarcode_NoRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบบาร์โค้ด.
        /// </summary>
        public static string RSBarcode_Null {
            get {
                return ResourceManager.GetString("RSBarcode_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบบาร์โค้ดผ่าน.
        /// </summary>
        public static string RSBarcode_OK {
            get {
                return ResourceManager.GetString("RSBarcode_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สแกนบาร์โค้ดซ้ำ.
        /// </summary>
        public static string RSBarcode_Repeat {
            get {
                return ResourceManager.GetString("RSBarcode_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูลเรียบร้อย.
        /// </summary>
        public static string RSData_Saved {
            get {
                return ResourceManager.GetString("RSData_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำลังบันทึกข้อมูล.
        /// </summary>
        public static string RSData_Saving {
            get {
                return ResourceManager.GetString("RSData_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำลังอ่านข้อมูล.
        /// </summary>
        public static string RSData_StartReading {
            get {
                return ResourceManager.GetString("RSData_StartReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำลังอัปโหลดข้อมูล.
        /// </summary>
        public static string RSData_Uploading {
            get {
                return ResourceManager.GetString("RSData_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัปโหลดข้อมูลไม่สำเร็จ.
        /// </summary>
        public static string RSData_UploadNG {
            get {
                return ResourceManager.GetString("RSData_UploadNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัปโหลดข้อมูลสำเร็จ.
        /// </summary>
        public static string RSData_UploadOK {
            get {
                return ResourceManager.GetString("RSData_UploadOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสอุปกรณ์ไม่ผ่าน.
        /// </summary>
        public static string RSFixture_NG {
            get {
                return ResourceManager.GetString("RSFixture_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ต้องตรวจสอบอุปกรณ์.
        /// </summary>
        public static string RSFixture_NotRequire {
            get {
                return ResourceManager.GetString("RSFixture_NotRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสอุปกรณ์ผ่าน.
        /// </summary>
        public static string RSFixture_OK {
            get {
                return ResourceManager.GetString("RSFixture_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องตรวจสอบอุปกรณ์.
        /// </summary>
        public static string RSFixture_RequireValidate {
            get {
                return ResourceManager.GetString("RSFixture_RequireValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำลังตรวจสอบอุปกรณ์.
        /// </summary>
        public static string RSFixture_Validating {
            get {
                return ResourceManager.GetString("RSFixture_Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบวัสดุไม่ผ่าน.
        /// </summary>
        public static string RSMaterial_NG {
            get {
                return ResourceManager.GetString("RSMaterial_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบวัสดุผ่าน.
        /// </summary>
        public static string RSMaterial_OK {
            get {
                return ResourceManager.GetString("RSMaterial_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานี 1 ไม่มีข้อมูลบาร์โค้ดนี้.
        /// </summary>
        public static string RSStation_NoData {
            get {
                return ResourceManager.GetString("RSStation_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผลการทดสอบที่สถานี 1 เป็น NG.
        /// </summary>
        public static string RSStation_Station1NG {
            get {
                return ResourceManager.GetString("RSStation_Station1NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาทำการทดสอบที่สถานี 1 ให้เสร็จก่อน.
        /// </summary>
        public static string RSStation_TobeCompleted {
            get {
                return ResourceManager.GetString("RSStation_TobeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันผู้ใช้สำเร็จ.
        /// </summary>
        public static string RSUser_OfflineOK {
            get {
                return ResourceManager.GetString("RSUser_OfflineOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันผู้ใช้ไม่สำเร็จ.
        /// </summary>
        public static string RSUser_OnlineNG {
            get {
                return ResourceManager.GetString("RSUser_OnlineNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันผู้ใช้สำเร็จ.
        /// </summary>
        public static string RSUser_OnlineOK {
            get {
                return ResourceManager.GetString("RSUser_OnlineOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำลังตรวจสอบผู้ใช้.
        /// </summary>
        public static string RSUser_Verifing {
            get {
                return ResourceManager.GetString("RSUser_Verifing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึก.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขบัตรปัจจุบัน มีหลายบัญชีและไม่สามารถเข้าสู่ระบบด้วยบัตรรูด!.
        /// </summary>
        public static string serchType {
            get {
                return ResourceManager.GetString("serchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รอทำงาน.
        /// </summary>
        public static string Standby {
            get {
                return ResourceManager.GetString("Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลเริ่มต้นของระบบไม่สามารถลบได้.
        /// </summary>
        public static string SystemDefaultDataNotDel {
            get {
                return ResourceManager.GetString("SystemDefaultDataNotDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผลลัพธ์.
        /// </summary>
        public static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สำเร็จ.
        /// </summary>
        public static string UploadState_Failed {
            get {
                return ResourceManager.GetString("UploadState_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ในเครื่อง.
        /// </summary>
        public static string UploadState_Local {
            get {
                return ResourceManager.GetString("UploadState_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเร็จ.
        /// </summary>
        public static string UploadState_Success {
            get {
                return ResourceManager.GetString("UploadState_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขีดจำกัดบน.
        /// </summary>
        public static string UpperLimit {
            get {
                return ResourceManager.GetString("UpperLimit", resourceCulture);
            }
        }
    }
}
